/*==============================================================*/
/* DBMS name:      ORACLE Version 12c                           */
/* Created on:     5/26/2023 11:58:15 PM                        */
/*==============================================================*/


alter table TRANSACTION
    drop constraint FK_TRANSACT_HAVE_PRODUCT;

drop table USERADMIN cascade constraints;

drop table PRODUCT cascade constraints;

drop index HAVE_FK;

drop table TRANSACTION cascade constraints;

/*==============================================================*/
/* Table: USERADMIN                                             */
/*==============================================================*/
create table USERADMIN
(
    USERACCOUNT VARCHAR2(30) not null,
    PASSACCOUNT VARCHAR2(30),
    constraint PK_USERADMIN primary key (USERACCOUNT)
);

/*==============================================================*/
/* Table: PRODUCT                                               */
/*==============================================================*/
create table PRODUCT
(
    IDPROD       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAMEPROD     VARCHAR2(20),
    QUANTITYPROD INTEGER,
    PRICEPROD    FLOAT,
    COMPANYPROD  CHAR(1),
    constraint PK_PRODUCT primary key (IDPROD)
);

/*==============================================================*/
/* Table: TRANSACTION                                           */
/*==============================================================*/
create table TRANSACTION
(
    IDTRANS   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    IDPROD    INTEGER,
    NAMETRANS VARCHAR2(30),
    TYPETRANS VARCHAR2(30),
    OBSTRANS  VARCHAR2(150),
    constraint PK_TRANSACTION primary key (IDTRANS)
);

/*==============================================================*/
/* Index: HAVE_FK                                               */
/*==============================================================*/
create index HAVE_FK on TRANSACTION (
                                     IDPROD ASC
    );

alter table TRANSACTION
    add constraint FK_TRANSACT_HAVE_PRODUCT foreign key (IDPROD)
        references PRODUCT (IDPROD);

INSERT INTO PRODUCT (NAMEPROD, QUANTITYPROD, PRICEPROD, COMPANYPROD) VALUES ('Producto 1', 10, 100.0, 'B');
INSERT INTO PRODUCT (NAMEPROD, QUANTITYPROD, PRICEPROD, COMPANYPROD) VALUES ('Producto 2', 20, 200.0, 'B');
INSERT INTO PRODUCT (NAMEPROD, QUANTITYPROD, PRICEPROD, COMPANYPROD) VALUES ('Producto 3', 30, 300.0, 'B');

INSERT INTO TRANSACTION (IDPROD, NAMETRANS, TYPETRANS, OBSTRANS)
VALUES (1, 'Compra de productos', 'Compra', 'Compra de productos de la tienda en línea');

INSERT INTO USERADMIN VALUES ('admin', 'admin');

