[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.163", features=["derive"]}
serde_yaml = "0.9.21"
rocket = "=0.5.0-rc.3"
reqwest = "0.11.18"
serde_json = "1.0"
rocket_contrib = "0.4"
lazy_static = "1.4.0"

